<?php
$language = array(
  array(
    "header" => "Ilmoittautuminen",
    "fieldset-1" => "Pilotti",
    "fieldset-2" => "Kone",
    "fieldset-3" => "Kilpailuluokka",
    "fieldset-4" => "Lennon tallentimet",
    "fieldset-5" => "Majoitus",
    "select-option-winglets-1" => "Valitse",
    "select-option-winglets-2" => "Kyllä",
    "select-option-winglets-3" => "Ei",
    "select-option-engine-1" => "Valitse",
    "select-option-engine-2" => "Itselähtevä",
    "select-option-engine-3" => "Kotiinpaluu",
    "select-option-engine-4" => "Ei moottoria",
    "label-pilot-first-name" => "Etunimi",
    "label-pilot-last-name" => "Sukunimi",
    "label-pilot-phone" => "Puhelin",
    "label-pilot-email" => "Sähköposti",
    "label-pilot-club" => "Kerho",
    "label-plane-type" => "Kone",
    "label-plane-register" => "Rekisterinumero",
    "label-plane-competition-sign" => "Kilpailutunnus",
    "label-plane-wingspan" => "Kärkiväli",
    "label-plane-winglets" => "Wingletit",
    "label-plane-engine" => "Moottori",
    "label-logger-1" => "Ykköstallennin",
    "label-logger-2" => "Kakkostallennin",
    "label-checkbox-logger-files"=>"Lähetän tiedostot myöhemmin",
  ),
  array(
    "header" => "Enrollment",
    "fieldset-1" => "Pilot",
    "fieldset-2" => "Plane",
    "fieldset-3" => "Competition class",
    "fieldset-4" => "Flight loggers",
    "fieldset-5" => "Accomodation",
    "select-option-winglets-1" => "Choose",
    "select-option-winglets-2" => "Yes",
    "select-option-winglets-3" => "No",
    "select-option-engine-1" => "Choose",
    "select-option-engine-2" => "Self launch",
    "select-option-engine-3" => "Turbo",
    "select-option-engine-4" => "No engine",
    "label-pilot-first-name" => "First name",
    "label-pilot-last-name" => "Last name",
    "label-pilot-phone" => "Phone",
    "label-pilot-email" => "Email",
    "label-pilot-club" => "Club",
    "label-plane-type" => "Plane",
    "label-plane-register" => "Register number",
    "label-plane-competition-sign" => "Competition sign",
    "label-plane-wingspan" => "Wing span",
    "label-plane-winglets" => "Winglets",
    "label-plane-engine" => "Engine",
    "label-logger-1" => "Primary logger",
    "label-logger-2" => "Secondary logger",
    "label-checkbox-logger-files"=>"I send the files later",
  )
)
?>
